% demo_EnsembleClustering_TRPCA_Caltech101_7
% demo_EnsembleClustering_TRPCA_Caltech101_20
% demo_EnsembleClustering_TRPCA_CCV
demo_EnsembleClustering_TRPCA_digit5
demo_EnsembleClustering_TRPCA_ALOI100

demo_EnsembleClustering_TRPCA_scene15
demo_EnsembleClustering_TRPCA_CMU_PIE_80_NEW
demo_EnsembleClustering_TRPCA_MITIndoor
